### ISSUE TITLE
PRODUCTS- FILTRO -CLIENT

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/PROJETO6-02#108]
- [x] Estrutura NAV de filtro
- [x] Estilo NAV de filtro
- [x] onClick em cada link settando um useState de URL pra ser utilizado dinamicamente na chamada API
- [x] Refactor de chamada API
- [x] Converter Chamada API pra Custom Hook
