### ISSUE TITLE
SERVER: SECURITY

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/PROJETO6-02#131]
- [ ] Sanitizacao de Input
- [ ] XSS protecao
- [ ]  Headers seguro
- [ ] Max numero de chamada
- [ ] Protecao de NOSQL injection
