### ISSUE TITLE
EPIC: CART- SERVER

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/PROJETO6-02#33]
- [ ] Rota para adicionar item
- [ ] Rota para remover item
- [ ] Rota para limpar o carrinho de vez
