### ISSUE TITLE
PRODUCTS EPIC

### ISSUE THREAD

**Issue by Medic1111** [Medic1111/PROJETO6-02#71]
- SERVER:
  - [x] Criar modelo DB Productos
  - [x] Criar Array produtos falsos
  - [x] Criar Rota GET todos os productos

- CLIENT:
  - [x] Criar pagina Productos: Estrutura
  - [x] Stilizar pagina productos
  - [x] Fetch API produtos
  - [x] Renderizar produtos pegos da API
